#**Trabalhando com Planilhas do Excel**

In [3]:
import pandas as pd

In [6]:
df_aracaju = pd.read_excel("/content/drive/MyDrive/Datasets/Aracaju.xlsx")
df_fortaleza = pd.read_excel("/content/drive/MyDrive/Datasets/Fortaleza.xlsx")
df_natal = pd.read_excel("/content/drive/MyDrive/Datasets/Natal.xlsx")
df_recife = pd.read_excel("/content/drive/MyDrive/Datasets/Recife.xlsx")
df_salvador = pd.read_excel("/content/drive/MyDrive/Datasets/Salvador.xlsx")

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
df = pd.concat([df_aracaju,df_fortaleza,df_natal,df_recife,df_salvador])

In [9]:
df.head()

    Cidade       Data  Vendas  LojaID  Qtde
0  Aracaju 2018-01-01  142.00    1520     1
1  Aracaju 2018-01-01   14.21    1522     6
2  Aracaju 2018-01-01   71.55    1520     1
3  Aracaju 2018-01-01    3.01    1521     7
4  Aracaju 2018-01-01   24.51    1522     8

In [10]:
df.tail()

       Cidade       Data  Vendas  LojaID  Qtde
235  Salvador 2019-01-03   41.84    1034     1
236  Salvador 2019-01-03  126.29    1035     3
237  Salvador 2019-01-03   38.06    1036     3
238  Salvador 2019-01-03  139.64    1035     1
239  Salvador 2019-01-03  161.41    1037     3

In [11]:
df.sample(5)

        Cidade       Data  Vendas  LojaID  Qtde
111      Natal 2019-01-02  147.35    1037     2
54   Fortaleza 2019-01-01   16.73    1002     5
56     Aracaju 2018-01-01   41.90    1523     6
117  Fortaleza 2019-03-02   15.42     983     8
45      Recife 2019-01-01   15.90     983     8

In [12]:
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID             int64
Qtde               int64
dtype: object

In [13]:
df["LojaID"] = df["LojaID"].astype("object")

In [14]:
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID            object
Qtde               int64
dtype: object

**Tratando valores faltantes**

In [16]:
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [17]:
df["Vendas"].fillna(df["Vendas"].mean(), inplace=True)

In [18]:
df["Vendas"].mean()

122.61180089485438

In [19]:
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [20]:
df.sample(15)

        Cidade       Data  Vendas LojaID  Qtde
104    Aracaju 2018-01-01   46.96   1522     1
2    Fortaleza 2019-02-10   35.33   1004     3
162   Salvador 2019-01-02   23.08   1036     2
198      Natal 2019-01-02   13.65   1037     3
9        Natal 2018-05-02  261.00    852     3
79     Aracaju 2018-01-01    5.59   1521     4
6       Recife 2019-01-01   16.27    981     6
133   Salvador 2019-03-02  153.71   1035     1
96     Aracaju 2018-01-01   85.92   1521     2
124      Natal 2019-01-02   44.82   1034     3
48    Salvador 2019-01-01  127.28   1035     2
88    Salvador 2019-01-01   31.20   1036     1
215   Salvador 2019-01-02  203.84   1036     1
62       Natal 2018-02-10  793.00    854     4
76     Aracaju 2018-01-01   33.51   1523     4

In [21]:
df["Vendas"].fillna(0, inplace=True)

In [22]:
df.dropna(inplace=True)

In [23]:
df.dropna(subset=["Vendas"], inplace=True)

In [24]:
df.dropna(how="all", inplace=True)

**Criando colunas novas**

In [25]:
df["Receita"] = df["Vendas"].mul(df["Qtde"])

In [26]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita
0  Aracaju 2018-01-01  142.00   1520     1   142.00
1  Aracaju 2018-01-01   14.21   1522     6    85.26
2  Aracaju 2018-01-01   71.55   1520     1    71.55
3  Aracaju 2018-01-01    3.01   1521     7    21.07
4  Aracaju 2018-01-01   24.51   1522     8   196.08

In [27]:
df["Receita/Vendas"] = df["Receita"] / df["Vendas"]

In [28]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
0  Aracaju 2018-01-01  142.00   1520     1   142.00             1.0
1  Aracaju 2018-01-01   14.21   1522     6    85.26             6.0
2  Aracaju 2018-01-01   71.55   1520     1    71.55             1.0
3  Aracaju 2018-01-01    3.01   1521     7    21.07             7.0
4  Aracaju 2018-01-01   24.51   1522     8   196.08             8.0

In [31]:
df.nlargest(3, "Receita")

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0

In [32]:
df.nsmallest(3, "Receita")

      Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
118  Aracaju 2018-01-01    3.34   1522     1     3.34             1.0
65    Recife 2019-01-01    4.01    981     1     4.01             1.0
92     Natal 2019-01-02    4.57   1035     1     4.57             1.0

In [33]:
df.groupby("Cidade")["Receita"].sum()

Cidade
Aracaju       48748.25
Fortaleza     37913.97
Natal        167227.52
Recife        51936.51
Salvador      40596.73
Name: Receita, dtype: float64

In [34]:
df.sort_values("Receita", ascending=False).head(10)

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
30  Natal 2018-10-02   856.0    853     4   3424.0             4.0
41  Natal 2018-05-20   835.0    852     4   3340.0             4.0
38  Natal 2018-02-25   828.0    852     4   3312.0             4.0
10  Natal 2018-10-27   828.0    852     4   3312.0             4.0
69  Natal 2019-03-24   817.0    852     4   3268.0             4.0
62  Natal 2018-02-10   793.0    854     4   3172.0             4.0
52  Natal 2018-04-27   778.0    854     4   3112.0             4.0

#**Trabalhando com datas**

In [35]:
df["Data"] = df["Data"].astype("int64")

In [36]:
df["Data"] = pd.to_datetime(df["Data"])

In [37]:
df.dtypes

Cidade                    object
Data              datetime64[ns]
Vendas                   float64
LojaID                    object
Qtde                       int64
Receita                  float64
Receita/Vendas           float64
dtype: object

In [38]:
df.groupby(df["Data"].dt.year)["Receita"].sum()

Data
2018    118176.53
2019    228246.45
Name: Receita, dtype: float64

In [48]:
df["Ano_Venda"], df["Mes_Venda"] = df["Data"].dt.year, df["Data"].dt.month

In [49]:
df.sample(5)

        Cidade       Data  Vendas  ... diferenca_dias  trimestre_venda  Mes_Venda
103     Recife 2019-01-01   41.65  ...       365 days                1          1
54   Fortaleza 2019-01-01   16.73  ...       365 days                1          1
53     Aracaju 2018-01-01    8.64  ...         0 days                1          1
41       Natal 2018-05-20  835.00  ...       139 days                2          5
233   Salvador 2019-01-03  172.40  ...       367 days                1          1

[5 rows x 11 columns]

In [50]:
df["Data"].min()

Timestamp('2018-01-01 00:00:00')

In [51]:
df["diferenca_dias"] = df["Data"] - df["Data"].min()

In [52]:
df.sample(5)

        Cidade       Data  Vendas  ... diferenca_dias  trimestre_venda  Mes_Venda
66     Aracaju 2018-01-01   76.59  ...         0 days                1          1
127      Natal 2019-01-02  240.61  ...       366 days                1          1
79      Recife 2019-01-01   14.53  ...       365 days                1          1
133  Fortaleza 2019-03-02   14.67  ...       425 days                1          3
94       Natal 2019-01-02   33.24  ...       366 days                1          1

[5 rows x 11 columns]

In [44]:
df["trimestre_venda"] = df["Data"].dt.quarter

In [53]:
df.sample(5)

        Cidade       Data  Vendas  ... diferenca_dias  trimestre_venda  Mes_Venda
89    Salvador 2019-01-01   17.46  ...       365 days                1          1
76   Fortaleza 2019-01-01   38.61  ...       365 days                1          1
74     Aracaju 2018-01-01    7.86  ...         0 days                1          1
121      Natal 2019-01-02  100.70  ...       366 days                1          1
135      Natal 2019-01-02    9.95  ...       366 days                1          1

[5 rows x 11 columns]

In [54]:
vendas_marco_19 = df.loc[(df["Data"].dt.year == 2019) & (df["Data"].dt.month == 3)]

In [55]:
vendas_marco_19.sample(20)

        Cidade       Data  Vendas  ... diferenca_dias  trimestre_venda  Mes_Venda
46       Natal 2019-03-26  753.00  ...       449 days                1          3
116   Salvador 2019-03-02   41.78  ...       425 days                1          3
120   Salvador 2019-03-02  140.17  ...       425 days                1          3
32       Natal 2019-03-17  244.00  ...       440 days                1          3
127  Fortaleza 2019-03-02   39.56  ...       425 days                1          3
141   Salvador 2019-03-02    9.08  ...       425 days                1          3
131     Recife 2019-03-02  139.07  ...       425 days                1          3
108  Fortaleza 2019-03-02  152.89  ...       425 days                1          3
45       Natal 2019-03-11  431.00  ...       434 days                1          3
82       Natal 2019-03-07  868.00  ...       430 days                1          3
138  Fortaleza 2019-03-02  150.38  ...       425 days                1          3
2        Natal 2019-03-11  308.00  ...       434 days                1          3
122     Recife 2019-03-02  235.06  ...       425 days                1          3
119     Recife 2019-03-02  152.30  ...       425 days                1          3
114  Fortaleza 2019-03-02   16.82  ...       425 days                1          3
136   Salvador 2019-03-02   13.81  ...       425 days                1          3
134   Salvador 2019-03-02  125.90  ...       425 days                1          3
125  Fortaleza 2019-03-02   37.60  ...       425 days                1          3
128   Salvador 2019-03-02   36.84  ...       425 days                1          3
136     Recife 2019-03-02   39.09  ...       425 days                1          3

[20 rows x 11 columns]